name: cage_cli
description: Command line interface for cage framework. The cli can be used to generate boilerplate source filed like services and widgets.
version: 0.1.0
author: Rouven T. Kruse <mail@rouvenkruse.de>
homepage: https://github.com/RTK/cage_cli

environment:
  sdk: '>=2.4.0 <3.0.0'

executables:
  cage_cli:

dependencies:
  args: ^1.5.2
  dart_style: ^1.2.9
  logging: ^0.11.3+2
  meta: 1.1.7
  mustache: ^1.1.1
  path: ^1.6.2
  resource: ^2.1.6
  test_coverage: ^0.3.0+1
  yaml: ^2.1.16

dev_dependencies:
  test: ^1.6.5
